# Copyright (C) 2026 Jonas Karlsson
# SPDX-License-Identifier: GPL-3.0-or-later

# Writes the version header. Runs on every build (cmake -P), since a new
# commit or tag doesn't reconfigure the project. Rewrites the header only when
# the version changes. Expects SOURCE_DIR, OUTPUT and PROJECT_VERSION.
#
# The version is `git describe --long` without the tag's "v":
#
#   0.1.0-0-g91ec34f        the v0.1.0 tag itself
#   0.1.0-5-g91ec34f        five commits past it
#   0.1.0-5-g91ec34f-dirty  with uncommitted changes
#
# Without a tag it's project()'s version plus the hash; without git,
# project()'s version alone.

set(version "${PROJECT_VERSION}")

find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" describe --tags --long --dirty --always
                --abbrev=7 --match "v[0-9]*"
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE describe
        RESULT_VARIABLE result
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
    )
    if(result EQUAL 0)
        if(describe MATCHES "^v(.*)$")
            set(version "${CMAKE_MATCH_1}")

            # On a tagged commit, the tag must match project()'s version, or the release
            # would report two different versions. A suffix (v0.2.0-rc1) is allowed.
            if(describe MATCHES "^v(.+)-0-g[0-9a-f]+(-dirty)?$")
                set(tag_version "${CMAKE_MATCH_1}")
                string(REPLACE "." "\\." project_version_pattern "${PROJECT_VERSION}")
                if(NOT tag_version STREQUAL PROJECT_VERSION
                   AND NOT tag_version MATCHES "^${project_version_pattern}-")
                    message(FATAL_ERROR
                        "The tag on this commit is v${tag_version}, but "
                        "project() in CMakeLists.txt says ${PROJECT_VERSION}. "
                        "Set project(VERSION) to match, then tag that commit.")
                endif()
            endif()
        elseif(NOT describe STREQUAL "")
            # No tag, just a hash.
            set(version "${PROJECT_VERSION}-g${describe}")
        endif()
    endif()
endif()

set(content "// Generated by cmake/Version.cmake on every build. Do not edit.
#pragma once
#define OBS_PUPPETEER_VERSION \"${version}\"
")

if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
endif()
if(NOT existing STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
